---
controller_execution_environments:
  - name: "EE_AWX_Livecycle_Molecule_Yamlint_Sign"
    description: ""
    image: "quay.io/adelahoz/ee_awx_livecycle_molecule_yamllint_sign:latest"
    pull: ""
  - name: "EE_AWX_Livecycle_AnsibleLint"
    description: ""
    image: "quay.io/adelahoz/ee_awx_livecycle_ansiblelint:latest"
    pull: ""
  - name: "EE_AWX_Filetree_dispatch"
    description: ""
    image: "quay.io/adelahoz/ee_awx_filetree_dispatch:latest"
    pull: ""
...
