---
controller_execution_environments:
  - name: "AWX EE (24.6.1)"
    description: ""
    image: "quay.io/ansible/awx-ee:24.6.1"
    pull: ""
  - name: "AWX EE (latest)"
    description: ""
    image: "quay.io/ansible/awx-ee:latest"
    pull: ""
  - name: "Control Plane Execution Environment"
    description: ""
    image: "quay.io/ansible/awx-ee:24.6.1"
    pull: ""
  - name: "EE_AWX_Livecycle"
    description: ""
    image: "quay.io/adelahoz/ee_awx_livecycle:latest"
    pull: ""
  - name: "EE_AWX_Filetree_dispatch"
    description: ""
    image: "quay.io/adelahoz/ee_awx_filetree_dispatch:latest"
    pull: ""
...
