---
- name: Manage Controller Credential Input Sources Block
  vars:
    ansible_async_dir: "{{ controller_configuration_async_dir }}"
  no_log: "{{ controller_configuration_credential_input_sources_secure_logging }}"
  block:
    - name: Managing Controller Credential Input Sources
      credential_input_source:
        target_credential: "{{ __cred_input_src_item.target_credential | mandatory }}"
        input_field_name: "{{ __cred_input_src_item.input_field_name | mandatory }}"
        source_credential: "{{ __cred_input_src_item.source_credential | default(omit, true) }}"
        description: "{{ __cred_input_src_item.description | default(('' if controller_configuration_credential_input_sources_enforce_defaults else omit), true) }}"
        metadata: "{{ __cred_input_src_item.metadata | default(({} if controller_configuration_credential_input_sources_enforce_defaults else omit), true) }}"
        state: "{{ __cred_input_src_item.state | default(controller_state | default('present')) }}"

        # Role specific options
        controller_username: "{{ controller_username | default(omit, true) }}"
        controller_password: "{{ controller_password | default(omit, true) }}"
        controller_oauthtoken: "{{ controller_oauthtoken | default(omit, true) }}"
        request_timeout: "{{ controller_request_timeout | default(omit, true) }}"
        controller_host: "{{ controller_hostname | default(omit, true) }}"
        controller_config_file: "{{ controller_config_file | default(omit, true) }}"
        validate_certs: "{{ controller_validate_certs | default(omit) }}"
      loop: "{{ controller_credential_input_sources }}"
      loop_control:
        loop_var: __cred_input_src_item
        label: "{{ __operation.verb }} Controller Credential Input Source for Credential {{ __cred_input_src_item.target_credential }}"
        pause: "{{ controller_configuration_credential_input_sources_loop_delay }}"
      async: "{{ ansible_check_mode | ternary(0, 1000) }}"
      poll: 0
      register: __credential_input_sources_job_async
      changed_when: (__credential_input_sources_job_async.changed if ansible_check_mode else false)
      vars:
        __operation: "{{ operation_translate[__cred_input_src_item.state | default(controller_state) | default('present')] }}"

    - name: Flag for errors (check mode only)
      ansible.builtin.set_fact:
        error_flag: true
      when: ansible_check_mode and __credential_input_sources_job_async.failed is defined and __credential_input_sources_job_async.failed

    - name: Managing Controller Credential Input Sources | Wait for finish the Controller Credential Input Sources management
      when:
        - not ansible_check_mode
        - __credential_input_sources_job_async_results_item.ansible_job_id is defined
      ansible.builtin.include_role:
        name: infra.controller_configuration.collect_async_status
      loop: "{{ __credential_input_sources_job_async.results }}"
      loop_control:
        loop_var: __credential_input_sources_job_async_results_item
        label: "{{ __operation.verb }} Controller Credential Input Source for Credential {{ __credential_input_sources_job_async_results_item.__cred_input_src_item.target_credential
          }}"
      vars:
        cas_secure_logging: "{{ controller_configuration_credential_input_sources_secure_logging }}"
        cas_async_delay: "{{ controller_configuration_credential_input_sources_async_delay }}"
        cas_async_retries: "{{ controller_configuration_credential_input_sources_async_retries }}"
        cas_job_async_results_item: "{{ __credential_input_sources_job_async_results_item }}"
        cas_error_list_var_name: "controller_credential_input_sources_errors"
        __operation: "{{ operation_translate[__credential_input_sources_job_async_results_item.__cred_input_src_item.state | default(controller_state) | default('present')]
          }}"

  always:
    - name: Cleanup async results files
      when:
        - not ansible_check_mode
        - __credential_input_sources_job_async_results_item.ansible_job_id is defined
      ansible.builtin.async_status:
        jid: "{{ __credential_input_sources_job_async_results_item.ansible_job_id }}"
        mode: cleanup
      loop: "{{ __credential_input_sources_job_async.results }}"
      loop_control:
        loop_var: __credential_input_sources_job_async_results_item
        label: "Cleaning up job results file: {{ __credential_input_sources_job_async_results_item.results_file | default('Unknown') }}"
...
